language: java
jdk:
    - oraclejdk7
    - openjdk7
# Do not install anything so that we can use our custom script. Instead, just
# return true.
#install: true
install: travis_retry mvn install
#script: "./travis-build.sh"
